projects:
  app:
    # path to YOUR gql schema
    schemaPath: 'src/schema.graphql'
    extensions:
      endpoints:
        # your graphql endpoint (not playground url!)
        default: 'http://localhost:4000'
  prisma:
    # where you want to generate the PRISMA graphql schema
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      # path to the prisma.yml
      prisma: 'prisma/prisma.yml'
